version: 0.0
os: linux
files:
  - source: /files/gunicorn.service
    destination: /etc/systemd/system/
  - source: /
    destination: /home/ubuntu/ChatApp-Django
perChatt: /home/ubuntu/ChatApp-Django
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/installDependecies.sh
      timeout: 300
      runas: ubuntu
