version: 0.0
os: linux
files:
  - source: /files/gunicorn.service
    destination: /etc/systemd/system/
  - source: /files/ChatApp-Django
    destination: /etc/nginx/sites-available/
  - source: /
    destination: /home/ubuntu/
permissions:
  - object: /home/ubuntu/
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/installDependecies.sh
      timeout: 300
      runas: root
    - location: scripts/restartngix.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stopnginx.sh
      timeout: 300
      runas: root
